-- AlterTable
ALTER TABLE "User" ALTER COLUMN "dni" DROP NOT NULL,
ALTER COLUMN "fecha_nac" DROP NOT NULL,
ALTER COLUMN "telefono" DROP NOT NULL,
ALTER COLUMN "direccion" DROP NOT NULL,
ALTER COLUMN "rol" SET DEFAULT 'PACIENTE';
